# Generated by Django 4.0.4 on 2022-04-28 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_feedback_project_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
            preserve_default=False,
        ),
    ]
